apiVersion: v1
kind: Secret
metadata:
  name: targeting-db-secret
  namespace: togglemaster
type: Opaque
stringData:
  POSTGRES_HOST: targeting-db.cxbowapyjusr.us-east-1.rds.amazonaws.com
  POSTGRES_DB: targeting_db
  POSTGRES_USER: tm_user
  POSTGRES_PASSWORD: tm_pass_26

  # Os valores DEVEM estar em base64
  #POSTGRES_USER: dG1fdXNlcg==
  #POSTGRES_PASSWORD: dG1fcGFzcw==
  #POSTGRES_DB: dGFyZ2V0aW5nX2Ri
