apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  POSTGRES_PASSWORD: tm_pass_26
  AUTH_SERVICE_KEY: some-secret-key  # se necess√°rio
