apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: togglemaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:3.0
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          ports:
            - containerPort: 4566
          envFrom:
            - secretRef:
                name: localstack-app-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 4566
            initialDelaySeconds: 5
            periodSeconds: 10

          volumeMounts:
            - name: localstack-data
              mountPath: /var/lib/localstack
            - name: init-script
              mountPath: /etc/localstack/init/ready.d/localstack-init.sh
              subPath: localstack-init.sh

      volumes:
        - name: localstack-data
          persistentVolumeClaim:
            claimName: localstack-pvc
        - name: init-script
          configMap:
            name: localstack-init
            defaultMode: 0755