apiVersion: v1
kind: Secret
metadata:
  name: localstack-app-secret
  namespace: togglemaster
type: Opaque
stringData:
  # Os valores DEVEM estar em base64
  SERVICES: sqs,dynamodb
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test