apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
  - ../namespaces/namespace.yaml
  - ../postgres/auth/secret.yaml
  - ../postgres/auth/pvc.yaml
  - ../postgres/auth/deployment.yaml
  - ../postgres/auth/service.yaml
  - ../postgres/flag/...
  - ../redis/service.yaml
  - ../redis/deployment.yaml
  - ../localstack/service.yaml
  - ../localstack/deployment.yaml
  - ../microservices/auth-service/deployment.yaml
  - ../microservices/auth-service/service.yaml
  - ../microservices/flag-service/...
  # etc. liste tudo que comp√µe o cluster
