apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: togglemaster
  labels:
    app: targeting-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
        - name: targeting-service
          image: 223517439672.dkr.ecr.us-east-1.amazonaws.com/targeting-service:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: targeting-service-config
                  key: PORT
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: targeting-service-config
                  key: DATABASE_URL
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: targeting-service-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: targeting-service-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: targeting-service-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: targeting-service-config
                  key: POSTGRES_HOST
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: targeting-service-config
                  key: AUTH_SERVICE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 10
