apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: togglemaster
type: Opaque
stringData:
  POSTGRES_HOST: auth-db.cxbowapyjusr.us-east-1.rds.amazonaws.com
  POSTGRES_DB: auth_db
  POSTGRES_USER: tm_user
  POSTGRES_PASSWORD: tm_pass_26
  
  # Os valores DEVEM estar em base64112
  ## POSTGRES_USER: dG1fdXNlcg==
  ## POSTGRES_PASSWORD: dG1fcGFzc18yNg==
  ## POSTGRES_DB: YXV0aF9kYg==
