apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: togglemaster
type: Opaque
data:
  # Os valores DEVEM estar em base64
  POSTGRES_USER: dG1fdXNlcg==
  POSTGRES_PASSWORD: dG1fcGFzcw==
  POSTGRES_DB: YXV0aF9kYg==
