apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: togglemaster
data:
  PORT: "8004"
  REDIS_URL: "rediss://togglemaster-redis-vwwz9q.serverless.use1.cache.amazonaws.com:6379"
  REDIS_PORT: "6379"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  SERVICE_API_KEY: "tm_key_6c03a7c3070f94318a7919e62ff1f30ca0213b06014016640f3115749a56656c"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/223517439672/togglemaster-queue"
  AWS_REGION: "us-east-1"
