apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: togglemaster
data:
  PORT: "8004"
  REDIS_URL: "redis://togglemaster-redis.vwwz9q.0001.use1.cache.amazonaws.com:6379"
  REDIS_PORT: "6379"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  SERVICE_API_KEY: "tm_key_07e90c1e649a14fe36a4b63facb586ab7066626dba708f8b394eaef262c20246"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/223517439672/togglemaster-queue"
  AWS_REGION: "us-east-1"
