apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: togglemaster
  labels:
    app: evaluation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: 223517439672.dkr.ecr.us-east-1.amazonaws.com/evaluation-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: 8004
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: PORT
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: REDIS_URL
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: REDIS_PORT
            - name: FLAG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: FLAG_SERVICE_URL
            - name: TARGETING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: TARGETING_SERVICE_URL
            - name: SERVICE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: SERVICE_API_KEY
            - name: AWS_SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: AWS_SQS_URL
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: AWS_REGION
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 10
